default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER') { 'root' } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { 'password' } %>
  host: db

development:
  <<: *default
  database: ggwp_development

test:
  <<: *default
  database: ggwp_test

  
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: ggwp_production
  username: ggwp
  password: <%= ENV['GGWP_DATABASE_PASSWORD'] %>